/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Document {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'uploadDate' : Time,
}
export type ExternalBlob = Uint8Array;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : { 'error' : string } };
export interface PaymentOrder {
  'id' : bigint,
  'paymentStatus' : OrderStatus,
  'billingAddress' : string,
  'customerPrincipal' : [] | [Principal],
  'createdAt' : Time,
  'fullName' : string,
  'amountCents' : [] | [bigint],
  'paymentCurrency' : [] | [string],
  'email' : string,
  'stripePaymentId' : [] | [string],
  'phone' : string,
  'items' : Array<ShoppingItem>,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : ProductCategory,
  'image' : [] | [ExternalBlob],
  'price' : [] | [bigint],
}
export type ProductCategory = { 'Accessories' : null } |
  { 'Computers' : null } |
  { 'Communication' : null } |
  { 'Networking' : null } |
  { 'Services' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<[string, ExternalBlob], string>,
  'addProduct' : ActorMethod<
    [
      string,
      ProductCategory,
      string,
      [] | [bigint],
      [] | [ExternalBlob],
      [] | [string],
      boolean,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<ShoppingItem>,
      [] | [bigint],
      [] | [string],
    ],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], Document>,
  'getMyOrders' : ActorMethod<[], Array<PaymentOrder>>,
  'getOrder' : ActorMethod<[bigint], PaymentOrder>,
  'getOrders' : ActorMethod<[], Array<PaymentOrder>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus, [] | [string]],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      ProductCategory,
      string,
      [] | [bigint],
      [] | [ExternalBlob],
      [] | [string],
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];